name: Braindump Builder

on:
  push:
    paths:
      - 'source.txt'
  
permissions:
  contents: write
  
jobs:
  call_reusable_workflow:
    uses: sarvjan/reusable-workflow/.github/workflows/get-dump.yml@main
    with:
      config: "source.txt"
